/**
 * This is a purpose-built Data Type Object (DTO) generator.
 *
 * It reads the openapi.yaml file, traverses the `#/components/schemas` section, and generates DTO objects
 * compatible for use with NestJS and React applications.  These DTO objects are decorated with
 * annotations from the NestJS Swagger library.
 */
import {generateDtos} from './nestjs';

const VERSION: string = '0.1.0';
const CONTROLLERS_DIRECTORY: string = 'src/generated/controllers';

(async () => {
  const fs = require('fs');
  const yaml = require('yaml');
  const { Command, Option } = require('commander');
  const program = new Command();
  const fileData = fs.readFileSync('./api/openapi.yaml', 'utf8');
  const openapi = yaml.parse(fileData);
  const generatorDirectories = fs.readdirSync('./', { recursive: true, withFileTypes: false })
    .filter((x) => {
      if (x.startsWith('node_modules')) {
        return false;
      }

      if (!x.startsWith('dist/')) {
        return false;
      }

      // Skip generated sources, and skip the generator - we want generator's builders, not the generator itself.
      if (x.includes('/generated') || x.endsWith('/generator')) {
        return false;
      }

      const stat = fs.statSync(x);

      return stat.isDirectory();
    })
    .map((x) => x.substring(x.lastIndexOf('/') + 1));

  program
    .option('-o, --out <directory>', 'output directory for generated controllers', CONTROLLERS_DIRECTORY)
    .addOption(new Option('-g <generator>', 'output generator to use').choices(generatorDirectories))
    .parse();

  console.log(`Controller Generator: ${VERSION}`);

  fs.rmSync(CONTROLLERS_DIRECTORY, { recursive: true, force: true });
  fs.mkdirSync(CONTROLLERS_DIRECTORY, { recursive: true });

  console.log(`Generating Controllers`);

  const controllerGenerator = require(`./${program.opts().g}`);

  controllerGenerator.generateControllers(program.opts().out, openapi);
})();


// import {initCap, propertyToType, toCamelCase} from './util';
//
// const VERSION = '0.1.0';
// const CONTROLLER_DIRECTORY = 'src/generated/controller';
// const HEADER = '/**\n * This file is automatically generated.\n * Do not modify this file, any changes will be overwritten.\n */\n\n';
//
// (async () => {
//   const fs = require('fs');
//   const yaml = require('yaml');
//   const fileData = fs.readFileSync('./api/openapi.yaml', 'utf8');
//   const openapi = yaml.parse(fileData);
//
//   console.log(`Controller Generator: ${VERSION}`);
//
//   fs.rmSync(CONTROLLER_DIRECTORY, { recursive: true, force: true });
//   fs.mkdirSync(CONTROLLER_DIRECTORY, { recursive: true });
//
//   console.log('Generating Controllers');
//
//   // const tags = {};
//   // const paths = openapi['paths'];
//   //
//   // for(const tag of openapi['tags']) {
//   //   tags[tag.name] = tag;
//   //   tags[tag.name]['body'] = '';
//   //   tags[tag.name]['refs'] = [];
//   // }
//   //
//   // for(const path of Object.keys(paths)) {
//   //   for(const [pathMethod, pathMethodData] of Object.entries(paths[path])) {
//   //     const pathTags = pathMethodData['tags'];
//   //     const pathName = path.replaceAll('{', ':').replaceAll('}', '');
//   //     const operationId = pathMethodData['operationId'];
//   //     const parameters = pathMethodData['parameters'] ?? [];
//   //     const requestBody = pathMethodData['requestBody'];
//   //     const responses = pathMethodData['responses'];
//   //     const bodyInputs = [];
//   //
//   //     for(const pathTag of pathTags) {
//   //       const description = pathMethodData['description'] ?? `${pathTag}: ${operationId}`;
//   //       let inputs = [];
//   //
//   //       for(const parameter of parameters) {
//   //         if (parameter['in'] === 'path') {
//   //           const parameterName = parameter['name'];
//   //           const parameterSchema = parameter['schema'];
//   //           const typescriptType = propertyToType(parameterSchema);
//   //
//   //           inputs.push(`@Param('${parameterName}') ${parameterName}: ${typescriptType}`);
//   //         } else {
//   //           console.log(`Parameter: ${JSON.stringify(parameter, null, 2)}`);
//   //         }
//   //       }
//   //
//   //       if (requestBody) {
//   //         inputs.push('@Body() body: any');
//   //
//   //         for (const [_, requestBodyData] of Object.entries(requestBody)) {
//   //           console.log(`Data: ${JSON.stringify(requestBodyData, null, 2)}`);
//   //         }
//   //       }
//   //
//   //       tags[pathTag]['body'] += `  /**\n   * ${description.replaceAll('\n', '\n   * ')}\n   */\n`;
//   //       tags[pathTag]['body'] += `  @${initCap(pathMethod)}('${pathName}')\n`;
//   //
//   //       for(const [responseStatus, responseData] of Object.entries(responses)) {
//   //         tags[pathTag]['body'] += `  @ApiResponse({ status: ${responseStatus}, description: '${responseData['description']}' })\n`;
//   //       }
//   //
//   //       tags[pathTag]['body'] += `  async ${operationId}(`;
//   //
//   //       if (inputs.length > 0) {
//   //         tags[pathTag]['body'] += '\n    ';
//   //         tags[pathTag]['body'] += inputs.join(',\n    ');
//   //         tags[pathTag]['body'] += '\n  ';
//   //       }
//   //
//   //       tags[pathTag]['body'] += '): Promise<any> {\n';
//   //
//   //       if (bodyInputs.length > 0) {
//   //         tags[pathTag]['body'] += bodyInputs.join(';\n    ');
//   //       }
//   //
//   //       tags[pathTag]['body'] += '    return null;\n';
//   //       tags[pathTag]['body'] += '  }\n\n';
//   //     }
//   //   }
//   // }
//   //
//   // for(const tag of Object.keys(tags)) {
//   //   const outFilename = `${CONTROLLER_DIRECTORY}/${tag}.controller.ts`;
//   //   const tagObject = tags[tag];
//   //   let classBody = '';
//   //
//   //   classBody += HEADER;
//   //   classBody += 'import { Post, Get, Delete, Options, Header, Put, Controller, Param, Body } from \'@nestjs/common\';\n';
//   //   classBody += 'import { ApiResponse } from \'@nestjs/swagger\';\n';
//   //
//   //   if (tagObject['refs'].length > 0) {
//   //     classBody += `import { ${tagObject['refs'].join(', ')} } from '../dto';\n`;
//   //   }
//   //
//   //   classBody += '\n';
//   //   classBody += `/**\n * ${(tagObject['description'] ?? tag).replaceAll('\n', '\n * ')}\n */\n`;
//   //   classBody += `@Controller('${toCamelCase(tag)}')\n`;
//   //   classBody += `export class ${tag}Controller {\n`;
//   //   classBody += tagObject['body'];
//   //   classBody += '}\n';
//   //
//   //   fs.writeFileSync(outFilename, classBody, 'utf8');
//   //   console.log(`  Wrote ${outFilename}`);
//   // }
// })();