import {initCap} from './util';

const VERSION = '0.1.0';
const CONTROLLER_DIRECTORY = 'src/generated/controller';
const HEADER = '/**\n * This file is automatically generated.\n * Do not modify this file, any changes will be overwritten.\n */\n\n';

(async () => {
  const fs = require('fs');
  const yaml = require('yaml');
  const fileData = fs.readFileSync('./api/openapi.yaml', 'utf8');
  const openapi = yaml.parse(fileData);

  console.log(`Controller Generator: ${VERSION}`);

  fs.rmSync(CONTROLLER_DIRECTORY, { recursive: true, force: true });
  fs.mkdirSync(CONTROLLER_DIRECTORY, { recursive: true });

  console.log('Generating Controllers');

  const tags = {};
  const paths = openapi['paths'];

  for(const tag of openapi['tags']) {
    tags[tag.name] = tag;
    tags[tag.name]['body'] = '';
  }

  for(const path of Object.keys(paths)) {
    for(const [pathMethod, pathMethodData] of Object.entries(paths[path])) {
      const pathTags = pathMethodData['tags'];
      const operationId = pathMethodData['operationId'];

      for(const pathTag of pathTags) {
        const description = pathMethodData['description'] ?? `${pathTag}: ${operationId}`;

        tags[pathTag]['body'] += `  /**\n   * ${description.replaceAll('\n', '\n   * ')}\n   */\n`;
        tags[pathTag]['body'] += `  @${initCap(pathMethod)}('${path}')\n`;
        tags[pathTag]['body'] += `  ${operationId}(): any {\n  }\n\n`;
      }
    }
  }

  for(const tag of Object.keys(tags)) {
    const outFilename = `${CONTROLLER_DIRECTORY}/${tag}.controller.ts`;
    const tagObject = tags[tag];
    let classBody = '';

    classBody += HEADER;
    classBody += 'import { Post, Get, Delete, Options, Header, Put } from \'@nestjs/common\';\n\n';
    classBody += `/**\n * ${(tagObject['description'] ?? tag).replaceAll('\n', '\n * ')}\n */\n`;
    classBody += `export class ${tag}Controller {\n`;
    classBody += tagObject['body'];
    classBody += '}\n';

    fs.writeFileSync(outFilename, classBody, 'utf8');
    console.log(`  Wrote ${outFilename}`);
  }
})();