/**
 * This is a purpose-built Data Type Object (DTO) generator.
 *
 * It reads the openapi.yaml file, traverses the `#/components/schemas` section, and generates DTO objects
 * compatible for use with NestJS and React applications.  These DTO objects are decorated with
 * annotations from the NestJS Swagger library.
 */

const VERSION = '0.1.0';
const DTO_DIRECTORY = 'src/generated/dto';
const HEADER = '/**\n * This file is automatically generated.\n * Do not modify this file, any changes will be overwritten.\n */\n\n';

export function typeFormatter(key: string, value: string) {
  if (key.toLowerCase() === 'type') {
    switch(value.toLowerCase()) {
      case 'number':
      case 'integer':
      case 'float':
      case 'double':
        return 'Number';

      case 'string':
        return 'String';

      case 'boolean':
        return 'Boolean';

      case 'object':
        return 'Object';

      case 'array':
        return 'Array';

      default:
        return value;
    }
  }

  return value;
}

export function propertyToType(properties: any): string {
  const type = properties['type'];
  const ref = properties['$ref'];

  if (ref) {
    return ref.substring(ref.lastIndexOf('/') + 1) + 'Dto';
  }

  if (properties['enum']) {
    return '[ ' + properties['enum'].map((x) => `'${x}'`).join(' | ') + ' ]';
  }

  switch(type.toLowerCase()) {
    case 'integer':
      return 'number';

    case 'array':
      return `${propertyToType(properties['items'])}[]`;
  }

  return type;
}

(async () => {
  const fs = require('fs');
  const yaml = require('yaml');
  const fileData = fs.readFileSync('./api/openapi.yaml', 'utf8');
  const openapi = yaml.parse(fileData);

  console.log(`DTO Generator: ${VERSION}`);

  fs.rmSync(DTO_DIRECTORY, { recursive: true, force: true });
  fs.mkdirSync(DTO_DIRECTORY, { recursive: true });

  console.log('Generating DTOs');

  const schemas = openapi['components']['schemas'];

  for(const dto of Object.keys(schemas)) {
    const dtoName = `${dto}Dto`;
    const dtoFilename = `${DTO_DIRECTORY}/${dto}.dto.ts`;
    const dtoDescription = schemas[dto]['description'];
    const dtoRequired = schemas[dto]['required'];
    const dtoHeader = HEADER;
    const dtoProperties = schemas[dto]['properties'];
    let dtoBody = '';

    // Add header to the class definition
    dtoBody += dtoHeader;
    dtoBody += 'import { ApiProperty } from \'@nestjs/swagger\';\n\n';
    dtoBody += `/**\n * ${dtoDescription.replaceAll('\n', '\n * ')}\n */\n`;
    dtoBody += `export class ${dtoName} {\n`;

    for(const property of Object.keys(dtoProperties)) {
      const propertiesDump = JSON.stringify(dtoProperties[property], typeFormatter, 2).replaceAll('\n', '\n  ');

      dtoBody += `  @ApiProperty(${propertiesDump.substring(0, propertiesDump.length - 1)}})\n`;
      dtoBody += `  ${property}: ${propertyToType(dtoProperties[property])};\n\n`;
    }

    dtoBody += '}\n';

    fs.writeFileSync(dtoFilename, dtoBody, 'utf8');
    console.log(`Wrote ${dtoFilename}`);
  }

  console.log(`Schemas: ${Object.keys(openapi['components']['schemas']).toString()}`);
})();
