import {initCap, propertyToType, toCamelCase, toKebabCase} from "../util";

const HEADER: string = `/**\n * This file is automatically generated.\n * Do not modify this file, any changes will be overwritten.\n *\n * Generated ${new Date()}\n */\n\n`;

export function generateControllers(directory: string, openApi: any) {
  const fs = require('fs');
  const tags: any = {};
  const paths = openApi.paths;
  const controllerDirectory = `${directory}/controllers`;

  fs.mkdirSync(controllerDirectory, { recursive: true });

  for (const tag of openApi.tags) {
    tags[tag.name] = tag;
    tags[tag.name].paths = [];
  }

  // Step 1: prepare a list of all paths associated with a tag.
  for (const path of Object.keys(paths)) {
    for (const [pathMethod, pathMethodData] of Object.entries(paths[path])) {
      for (const tag of pathMethodData['tags']) {
        tags[tag].paths.push({
          path,
          method: pathMethod,
          data: pathMethodData
        });
      }
    }
  }

  // Step 2: walk the list of tags, and write all controllers for each tag
  for (const tag of Object.keys(tags)) {
    const controllerName = tags[tag].name;
    const controllerDescription = tags[tag].description ?? '';

    generateController(controllerDirectory, controllerName, controllerDescription, tags[tag].paths);
  }

  // Write index
  let indexBody = HEADER;
  const indexFilename = `${controllerDirectory}/index.ts`;

  for(const tag of Object.keys(tags)) {
    indexBody += `export * from './${tag}.controller';\n`;
  }

  fs.writeFileSync(indexFilename, indexBody, 'utf8');
  console.log(`  + Wrote ${indexFilename}`);
}

function generateController(directory: string, name: string, description: string, paths: any[]) {
  const fs = require('fs');
  const controllerFile = `${directory}/${name}.controller.ts`;
  const controllerDtoImports = {};
  let controllerBody = '';
  let controllerClassBody = '';

  controllerBody += HEADER;

  controllerBody += 'import { Controller, Get, Delete, Post, Patch, Put, Options, Body, Param } from \'@nestjs/common\';\n';
  controllerBody += 'import { ApiResponse, ApiOperation, ApiBody, ApiTags } from \'@nestjs/swagger\';\n';
  controllerBody += `import { ${name}Service } from '../services';\n`;

  for (const pathEntry of paths) {
    const { path, method } = pathEntry;
    const { operationId, description, summary, parameters, requestBody, responses } = pathEntry.data;
    let convertedPath = path.replaceAll('{', ':').replaceAll('}', '');
    const requestBodyContent = requestBody?.content['application/json'];
    const inputs = [];
    const inputVariables = [];
    let returnType = null;

    // Trim converted path - first part of the URL is not required, as that is based on the URL of the
    // controller and ApiTags definition
    if (convertedPath.startsWith('/')) {
      convertedPath = convertedPath.substring(1);
    }

    if (convertedPath.indexOf('/') !== -1) {
      convertedPath = convertedPath.substring(convertedPath.indexOf('/'));
    } else {
      convertedPath = '';
    }

    controllerClassBody += `  /**\n   * ${description.trim().replaceAll('\n', '\n   * ')}\n   */\n`;

    if (convertedPath.length > 0) {
      controllerClassBody += `  @${initCap(method)}('${convertedPath}')\n`;
    } else {
      controllerClassBody += `  @${initCap(method)}()\n`;
    }

    controllerClassBody += '  @ApiOperation({\n';

    if (summary) {
      controllerClassBody += `    summary: '${summary}',\n`;
    }

    if (description) {
      controllerClassBody += `    description: '${description.trim().replaceAll('\n', ' ')}',\n`;
    }

    controllerClassBody += '  })\n';

    for (const [ responseCode, responseData ] of Object.entries(responses)) {
      const responseDescription = responseData['description'] ?? '';

      if (responseData['content']) {
        const content = responseData['content'];
        const contentCode = parseInt(responseCode);
        const contentTypes = Object.keys(content);

        if (contentCode >= 200 && contentCode <= 299) {
          const contentSchema = content[contentTypes[0]].schema;
          const contentSchemaType = propertyToType(contentSchema);

          if (contentTypes.length > 1) {
            throw new Error(`Path ${path}, method ${method}, return code ${contentCode} has more than one content type for operation ${operationId}`);
          }

          if (returnType) {
            returnType += ` | ${contentSchemaType}`;
          } else {
            returnType = contentSchemaType;
          }

          if (contentSchemaType.endsWith('Dto')) {
            controllerDtoImports[contentSchemaType] = 1;
          } else if (contentSchemaType.indexOf('[')) {
            if (contentSchemaType.substring(0, contentSchemaType.indexOf('[')).endsWith('Dto')) {
              controllerDtoImports[contentSchemaType.substring(0, contentSchemaType.indexOf('['))] = 1;
            }
          }
        }
      }

      controllerClassBody += `  @ApiResponse({ status: ${responseCode}, description: '${responseDescription.trim().replaceAll('\n', ' ')}' })\n`;
    }

    if (parameters) {
      for (const parameter of parameters) {
        const { name, description, schema } = parameter;
        const inPath = parameter.in;

        if (inPath.toLowerCase() === 'path') {
          const parameterSchema = propertyToType(schema);

          if (parameterSchema.endsWith('Dto')) {
            controllerDtoImports[parameterSchema] = 1;
          } else if (parameterSchema.indexOf('[')) {
            if (parameterSchema.substring(0, parameterSchema.indexOf('[')).endsWith('Dto')) {
              controllerDtoImports[parameterSchema.substring(0, parameterSchema.indexOf('['))] = 1;
            }
          }

          inputs.push(`@Param('${name}') ${name}: ${parameterSchema}`);
          inputVariables.push(name);
        }
      }
    }

    if (requestBodyContent) {
      const description = requestBody.description;
      const schema = requestBodyContent.schema;

      controllerClassBody += '  @ApiBody({\n';

      if (description) {
        controllerClassBody += `    description: '${description.trim().replaceAll('\n', ' ')}',\n`;
      }

      if (schema.$ref) {
        const reference = schema.$ref.substring(schema.$ref.lastIndexOf('/') + 1);

        inputs.push(`@Body() ${toCamelCase(reference)}Dto: ${reference}Dto`);
        inputVariables.push(`${toCamelCase(reference)}Dto`);
        controllerDtoImports[`${reference}Dto`] = 1;

        controllerClassBody += `    type: ${reference}Dto,\n`;
      }

      controllerClassBody += '  })\n';
    }

    controllerClassBody += `  public async ${operationId}(${inputs.join(', ')}): Promise<${returnType ?? 'void'}> {\n`;
    controllerClassBody += `    return this.service.${operationId}(${inputVariables.join(', ')});\n`;
    controllerClassBody += '  }\n\n';
  }

  if (Object.keys(controllerDtoImports).length > 0) {
    controllerBody += `import { ${Object.keys(controllerDtoImports).join(', ')} } from '../dto';\n`;
  }

  controllerBody += '\n';
  controllerBody += `/**\n * ${description.trim().replaceAll('\n', '\n * ')}\n */\n`;
  controllerBody += `@ApiTags('${toKebabCase(name)}')\n`;
  controllerBody += `@Controller('${toKebabCase(name)}')\n`;
  controllerBody += `export class ${name}Controller {\n\n`;
  controllerBody += `  constructor(private readonly service: ${name}Service) { }\n\n`;
  controllerBody += controllerClassBody;
  controllerBody += '}\n';

  fs.writeFileSync(controllerFile, controllerBody, 'utf8');
  console.log(`  - Wrote ${controllerFile}`);
}
