import {initCap, toCamelCase} from "../util";

const HEADER: string = `/**\n * This file is automatically generated.\n * Do not modify this file, any changes will be overwritten.\n *\n * Generated ${new Date()}\n */\n\n`;

export function generateControllers(controllerDirectory: string, openApi: any) {
  const fs = require('fs');
  const tags: any = {};
  const paths = openApi.paths;

  for (const tag of openApi.tags) {
    tags[tag.name] = tag;
    tags[tag.name].paths = [];
  }

  // Step 1: prepare a list of all paths associated with a tag.
  for (const path of Object.keys(paths)) {
    for (const [pathMethod, pathMethodData] of Object.entries(paths[path])) {
      for (const tag of pathMethodData['tags']) {
        tags[tag].paths.push({
          path,
          method: pathMethod,
          data: pathMethodData
        });
      }
    }
  }

  // Step 2: walk the list of tags, and write all controllers for each tag
  for (const tag of Object.keys(tags)) {
    const controllerName = tags[tag].name;
    const controllerDescription = tags[tag].description ?? '';

    generateController(controllerDirectory, controllerName, controllerDescription, tags[tag].paths);
  }
}

function generateController(directory: string, name: string, description: string, paths: any[]) {
  const fs = require('fs');
  const controllerFile = `${directory}/${name}.controller.ts`;
  const controllerDtoImports = {};
  let controllerBody = '';
  let controllerClassBody = '';

  controllerBody += HEADER;

  controllerBody += 'import { Controller, Get, Delete, Post, Patch, Put, Options, Body, Param } from \'@nestjs/common\';\n';
  controllerBody += 'import { ApiResponse, ApiOperation } from \'@nestjs/swagger\';\n';
  controllerBody += `import { ${name}Service } from '../services';\n`;

  for (const pathEntry of paths) {
    const { path, method } = pathEntry;
    const { operationId, description, summary, parameters, requestBody, responses } = pathEntry.data;
    const convertedPath = path.replaceAll('{', ':').replaceAll('}', '');
    const requestBodyContent = requestBody?.content['application/json'];
    const inputs = [];

    controllerClassBody += `  /**\n  * ${description.trim().replaceAll('\n', '\n  * ')}\n   */\n`;
    controllerClassBody += `  @${initCap(method)}('${convertedPath}')\n`;

    if (summary && description) {
      controllerClassBody += `  @ApiOperation({ summary: '${summary}', description: '${description.trim().replaceAll('\n', ' ')}' })\n`;
    } else if (summary) {
      controllerClassBody += `  @ApiOperation({ summary: '${summary}' })\n`;
    } else if (description) {
      controllerClassBody += `  @ApiOperation({ description: '${description.trim().replaceAll('\n', ' ')}' })\n`;
    }

    for (const [ responseCode, responseData ] of Object.entries(responses)) {
      const responseDescription = responseData['description'] ?? '';
      const responseContent = responseData['content'] ?? {};

      controllerClassBody += `  @ApiResponse({ status: ${responseCode}, description: '${responseDescription.trim().replaceAll('\n', ' ')}' })\n`;
    }

    if (requestBodyContent) {
      const schema = requestBodyContent.schema;

      if (schema.$ref) {
        const reference = schema.$ref.substring(schema.$ref.lastIndexOf('/') + 1);

        inputs.push(`@Body() ${toCamelCase(reference)}Dto: ${reference}Dto`);
        controllerDtoImports[`${reference}Dto`] = 1;
      }
    }

    controllerClassBody += `  public ${operationId}(${inputs.join(', ')}): any {\n`;
    controllerClassBody += `    return this.service.${operationId}();\n`;
    controllerClassBody += '  }\n\n';
  }

  if (Object.keys(controllerDtoImports).length > 0) {
    controllerBody += `import { ${Object.keys(controllerDtoImports).join(', ')} } from '../dto';\n`;
  }

  controllerBody += '\n';
  controllerBody += `/**\n * ${description.trim().replaceAll('\n', '\n * ')}\n */\n`;
  controllerBody += `@Controller('${toCamelCase(name)}')\n`;
  controllerBody += `export class ${name}Controller {\n`;
  controllerBody += `  constructor(private service: ${name}Service) { }\n\n`;
  controllerBody += controllerClassBody;

  controllerBody += `/*\n${JSON.stringify(paths, null, 2)}\n */\n\n`;

  controllerBody += '}\n';

  fs.writeFileSync(controllerFile, controllerBody, 'utf8');
  console.log(`  - Wrote ${controllerFile}`);
}
