// import {propertyToType, typeFormatter} from '../util';

const HEADER: string = `/**\n * This file is automatically generated.\n * Do not modify this file, any changes will be overwritten.\n *\n * Generated ${new Date()}\n */\n\n`;

export function generateDaos(directory: string, openapi: any) {
  const schemas = openapi.components.schemas;
  const dtoDirectory = `${directory}/dao`;
  const fs = require('fs');

  fs.mkdirSync(dtoDirectory, { recursive: true });

  for(const dao of Object.keys(schemas)) {
    const daoName = `${dao}Dao`;
    const daoFilename = `${dtoDirectory}/${dao}.dao.ts`;
    const daoHeader = HEADER;
    let daoBody = '';

    // Add header to the class definition
    daoBody += daoHeader;
    daoBody += `import { ${dao}Dto } from "../dto";\n`;
    daoBody += 'import { BaseDao } from "./BaseDao";\n\n';
    daoBody += `export class ${daoName} extends BaseDao<${dao}Dto> {\n`;
    daoBody += '  constructor() {\n';
    daoBody += `    super('${pascalToSnake(initLower(dao))}');\n`;
    daoBody += '  }\n';
    daoBody += '}\n';

    fs.writeFileSync(daoFilename, daoBody, 'utf8');
    console.log(`  - Wrote ${daoFilename}`);
  }
  //
  // // Write index
  // let indexBody = HEADER;
  // const indexFilename = `${dtoDirectory}/index.ts`;
  //
  // for(const dto of Object.keys(schemas)) {
  //   indexBody += `export * from './${dto}.dto';\n`;
  // }
  //
  // fs.writeFileSync(indexFilename, indexBody, 'utf8');
  // console.log(`  + Wrote ${indexFilename}`);
}

export function pascalToSnake(str: string): string {
  return str.replace(/([A-Z])/g, (match) => `_${match.toLowerCase()}`);
}

export function initLower(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1);
}