import {propertyToType, typeFormatter} from '../util';

const HEADER: string = `/**\n * This file is automatically generated.\n * Do not modify this file, any changes will be overwritten.\n *\n * Generated ${new Date()}\n */\n\n`;
const IMPORT_HEADER: string = 'import { ApiProperty, ApiPropertyOptional } from \'@nestjs/swagger\';\n\n';

export function generateDtos(dtoDirectory: string, openapi: any) {
  const schemas = openapi.components.schemas;
  const fs = require('fs');

  for(const dto of Object.keys(schemas)) {
    const { properties, description } = schemas[dto];
    const required: string[] = schemas[dto].required ?? [];
    const dtoName = `${dto}Dto`;
    const dtoFilename = `${dtoDirectory}/${dto}.dto.ts`;
    const dtoHeader = HEADER + IMPORT_HEADER;
    let dtoBody = '';

    // Add header to the class definition
    dtoBody += dtoHeader;
    dtoBody += `/**\n * ${description.trim().replaceAll('\n', '\n * ')}\n */\n`;
    dtoBody += `export class ${dtoName} {\n`;

    for(const property of Object.keys(properties)) {
      // This converts the properties section of the @ApiProperty section, each key is converted to use
      // no quotes, as it matches the name of the property interface.
      const propertiesDump = JSON.stringify(properties[property], typeFormatter, 2)
        .replaceAll('\n', '\n  ')
        .replace(/"([^"]+)":/g, '$1:');
      let requiredFlag = required.includes(property) ? '' : '?';
      let optionalFlag = required.includes(property) ? 'ApiProperty' : 'ApiPropertyOptional';

      dtoBody += `  @${optionalFlag}(${propertiesDump.substring(0, propertiesDump.length - 1)}})\n`;
      dtoBody += `  ${property}${requiredFlag}: ${propertyToType(properties[property])};\n\n`;
    }

    dtoBody += '}\n';

    fs.writeFileSync(dtoFilename, dtoBody, 'utf8');
    console.log(`  - Wrote ${dtoFilename}`);
  }

  // Write index
  let indexBody = HEADER;
  const indexFilename = `${dtoDirectory}/index.ts`;

  for(const dto of Object.keys(schemas)) {
    indexBody += `export * from './${dto}.dto';\n`;
  }

  fs.writeFileSync(indexFilename, indexBody, 'utf8');
  console.log(`  + Wrote ${indexFilename}`);
}