services:
  objectified-docs:
    container_name: objectified-docs
    expose:
      - ${PORT}
    ports:
      - "${PORT}:${PORT}"
    working_dir: /objectified-docs
    command: []
    environment:
      - PORT=${PORT}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REMOTE}/objectified-docs:${TAG_DOCS:-latest}
