import type { NextPage } from 'next';
import Head from 'next/head';

import Flow from 'components/Flow';

import styles from '../styles/Home.module.css';
import Sidebar from "../components/sidebar/sidebar";
import {ReactFlowProvider} from "@xyflow/react";
import {DnDProvider} from "../components/drag-and-drop/DnDContext";

const Home: NextPage = () => {
  return (
    <ReactFlowProvider>
      <DnDProvider>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
          </Head>

          <Sidebar />

          <header className={styles.header}>
            Objectified
          </header>

          <div className={styles.flow}>
            <Flow/>
          </div>
        </div>
      </DnDProvider>
    </ReactFlowProvider>
  );
};

export default Home;
