services:
  objectified-external:
    container_name: objectified-external
    expose:
      - "3001"
    ports:
      - "3001:3001"
    working_dir: /objectified/objectified-external
    entrypoint: ["yarn", "start"]
    command: []
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3001
    build:
      context: ../
      dockerfile: objectified-external/Dockerfile
    image: ${DOCKER_REMOTE}/objectified-external:${TAG_EXTERNAL:-latest}
