name: Objectified Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Set up latest Yarn with corepack
        run: corepack enable && corepack use yarn
