name: Objectified Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      NEXTAUTH_URL: http://localhost:3000/api/auth
      SERVICE_URL: http://localhost:3001/
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Set up latest Yarn with corepack
        run: corepack enable && corepack use yarn

      - name: Build API
        run: cd objectified-api && sh ./build.sh

      - name: Start PostgreSQL
        services:
          postgres:
            image: postgres:latest
            env:
              POSTGRES_PASSWORD: postgres
            options: >-
              --health-check-timeout=180s

      - name: Build Database Schema
        run: cd objectified-db && sh ./build.sh
