name: Objectified Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXTAUTH_URL: http://localhost:3000/api/auth
      SERVICE_URL: http://localhost:3001/
      UI_PORT: "3000"
      SERVICE_PORT: "3001"
      DOCKER_REMOTE: ${{ secrets.DOCKER_HOST }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TAG_DB: 0.0.10
      TAG_DOCS: 0.0.3
      TAG_SERVICES: 0.0.6
      TAG_EXTERNAL: 0.0.1
      TAG_UI: 0.0.22

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docs
        run: |
          cd objectified-docs
          PORT="${SERVICE_PORT}" docker compose build
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REMOTE}
          docker image push ${DOCKER_REMOTE}/objectified-docs:${TAG_DOCS}

      - name: Build Database
        run: |
          cd objectified-db
          docker compose build
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REMOTE}
          docker image push ${DOCKER_REMOTE}/objectified-db:${TAG_DB}

      - name: Build Service
        run: |
          cd objectified-services
          docker compose build
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REMOTE}
          docker image push ${DOCKER_REMOTE}/objectified-services:${TAG_SERVICES}

      - name: Build External
        run: |
          cd objectified-external
          docker compose build
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REMOTE}
          docker image push ${DOCKER_REMOTE}/objectified-external:${TAG_EXTERNAL}

      - name: Build UI
        run: |
          cd objectified-ui
          docker compose build
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REMOTE}
          docker image push ${DOCKER_REMOTE}/objectified-ui:${TAG_UI}
