name: Objectified Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      NEXTAUTH_URL: http://localhost:3000/api/auth
      SERVICE_URL: http://localhost:3001/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Set up latest Yarn with corepack
        run: corepack enable && corepack use yarn

      - name: Build API
        run: cd workspace-api && sh ./build.sh
